CREATE TABLE IF NOT EXISTS RESERVATION (
    RESERVATION_ID SMALLINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    RESERVATION_DATE DATE NOT NULL,
    RESERVATION_TIME_START TIME NOT NULL,
    RESERVATION_TIME_END TIME NOT NULL,
    TOTAL_AMOUNT DECIMAL(10,2) NOT NULL,
    TOTAL_DURATION TIME NOT NULL,
    FIRST_PARKING_RATE DECIMAL(10,2) NOT NULL,
    SUCCEEDING_RATE DECIMAL(10,2) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    CUST_ID SMALLINT NOT NULL,
    FLOOR_ID SMALLINT NOT NULL,
    PAYMENT_ID SMALLINT NOT NULL,
    DISCOUNT_ID SMALLINT NULL,
    FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID),
    FOREIGN KEY (FLOOR_ID) REFERENCES FLOOR_LEVEL(FLOOR_ID),
    FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENT(PAYMENT_ID),
    FOREIGN KEY (DISCOUNT_ID) REFERENCES DISCOUNT(DISCOUNT_ID)
); 