CREATE TABLE IF NOT EXISTS RESERVATION (
    RESERVATION_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    BLOCK_SPOT_ID INT NOT NULL,
    CUST_ID INT NOT NULL,
    VEHICLE_ID INT NOT NULL,
    RESERVATION_DATE DATE NOT NULL,
    RESERVATION_TIME_START DATETIME NOT NULL,
    RESERVATION_TIME_END DATETIME NOT NULL,
    TOTAL_DURATION TIME NOT NULL,
    FIRST_PARKING_RATE DECIMAL(10,2) NOT NULL,
    SUCCEEDING_RATE DECIMAL(10,2) NOT NULL,
    TOTAL_AMOUNT DECIMAL(10,2) NOT NULL,
    PAYMENT_ID INT,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'Active',
    FOREIGN KEY (BLOCK_SPOT_ID) REFERENCES BLOCK_SPOT(BLOCK_SPOT_ID),
    FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID),
    FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE(VEHICLE_ID),
    FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENT(PAYMENT_ID)
); 